security:

    role_hierarchy:
        ROLE_ADMIN: [ ROLE_USER, ROLE_COMPANY, ROLE_ALLOWED_TO_SWITCH ]

    encoders:
        AppBundle\Entity\WebAccount: bcrypt

    providers:
        web_accounts:
            entity: { class: 'AppBundle:WebAccount', property: 'username' }

    firewalls:
        dev:
            pattern: '^/(_(profiler|wdt)|css|images|js|pdf)/'
            security: false

        main:
            pattern:  '^/'
            anonymous: ~
            guard:
                authenticators: ['app.login_form_authenticator']
            logout:
                path: app_logout
                target: app_homepage

#    access_control:
#        - { path: '^/job/(?:\d+)/apply$', roles: ROLE_USER }
